openapi: 3.0.0
info:
  version: "v1"
  title: Bisnode company risk and credit data API
  description: >-
    Bisnode Company Risk and Credit data API
    
    Since we don't want to expose any personally identifiable information (PII) parameters in the URL,
    GET requests with a registrationNumber is not supported.
    
  contact:
    email: team-ninjas@bisnode.com
security:
  - implicit:
      - riskAndCredit
paths:
  /companies/se:
    post:
      summary: Fetch credit and risk data on a swedish company
      description: >-
        Fetch risk and credit data on swedish companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestModel'
            example: 
              mock: {"registrationNumber": "00000000000", "reason": "My important reason"}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
  /companies/fi:
    post:
      summary: Fetch credit and risk data on a finnish company
      description: >-
        Fetch risk and credit data on finnish companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestModel'
            example: 
              mock: {"registrationNumber": "00000000000", "reason": "My important reason"}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
  /companies/dk:
    post:
      summary: Fetch credit and risk data on a danish company
      description: >-
        Fetch risk and credit data on danish companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestModel'
            example: 
              mock: {"registrationNumber": "00000000000", "reason": "My important reason"}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
  /companies/no:
    post:
      summary: Fetch credit and risk data on a norwegian company
      description: >-
        Fetch risk and credit data on norwegian companies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestModel'
            example: 
              mock: {"registrationNumber": "00000000000", "reason": "My important reason"}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
                  
components:
  schemas:
    RequestModel:
      type: object
      description: The request model for credit data
      properties:
        registrationNumber: 
          type: string
          description: A national registrationNumber, can be a socialSecurityNumber for a Sole proprietor
        reason:
          type: string
          description: The reason why the client is requesting this data. The client needs a legitimate reason in certain situations. TODO - when ????
        language:
          type: string
          enum: ['SE', 'EN', 'NO', 'DK', 'FI']
          description: Supported languages for all the description fields where i18n is supported
          default: EN
      required: ['registrationNumber']
      title: RequestModel
    ResponseModel:
       $ref: 'https://api.swaggerhub.com/domains/bisnode-apis/SwedishCompanyCreditModel/1.0.0#/components/schemas/SwedishCompanyData'
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://login.bisnode.com/as/token.oauth2'
          scopes:
            riskAndCredit: allows access to Bisnode risk and credit data