# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: Bisnode Error Model
  description: This is the error model that all API's that follows the Bisnode API Guidelines must align with
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
    ErrorModel:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: http status code
          example: 200
        statusText:
          type: string
          description: http status code description
          example: BAD REQUEST
        message:
          type: string
          description: Description of the error
          example: Validation error
        subErrors:
          type: array
          description: A list of of the errors
          items:
            "$ref": '#/components/schemas/SubError'
        
    SubError:
      type: object
      description: A detailed view of an error
      properties:
        object:
          type: string
          description: which object does the error relate to
          example: Object x
        field:
          type: string
          description: which field on the object had an error
          example: size
        rejectedValue:
          type: string
          description: The value that was rejected
          example: 10
        message:
          type: string
          description: Detailed description of the error
          example: size must be greater than 10