# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: Bisnode Links Model
  description: Common model for linking
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
    Links:
      type: object
      description: Used for pagination
      properties:
        first:
          "$ref": '#/components/schemas/Link'
        next:
          "$ref": '#/components/schemas/Link'
        prev:
          "$ref": '#/components/schemas/Link'
        last:
          "$ref": '#/components/schemas/Link'
    Link:
      type: object
      required:
        - href
      properties:
        href:
          type: string
          description: A valid URI